package vn.skillbridge.projects.domain;

/** A reason a draft cannot yet enter review. Draft saves tolerate these; submission and publication do not. */
public enum ReadinessIssue {
    SUMMARY_REQUIRED,
    PROBLEM_REQUIRED,
    INDUSTRY_REQUIRED,
    SME_SIZE_REQUIRED,
    COMPLEXITY_REQUIRED,
    BUDGET_REQUIRED,
    DEADLINE_REQUIRED,
    DEADLINE_NOT_IN_FUTURE,
    SKILLS_REQUIRED,
    ACCEPTANCE_CRITERIA_REQUIRED,
    MILESTONES_REQUIRED,
    MILESTONE_TITLE_REQUIRED,
    MILESTONE_BUDGET_REQUIRED,
    MILESTONE_DEADLINE_REQUIRED,
    MILESTONE_DEADLINE_NOT_IN_FUTURE,
    MILESTONE_DEADLINE_AFTER_PROJECT,
    MILESTONE_BUDGET_MISMATCH,
    BUDGET_OUTSIDE_LEVEL_RANGE
}
